### PR TITLE
fix window compilation

### PR DESCRIPTION
**Pull request by Abergard**
added missing include

### CODE REVIEW

**Comment by mambolevis** [comment]
I tested the patch and only one error from three was fixed. This is my new test:
>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>Checking Build System
1>CMake does not need to re-run because C:/user/.emacs.d/user/site-lisp/irony-20170821.1300/build/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/user/.emacs.d/user/site-lisp/irony-20170821.1300/build/src/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/user/.emacs.d/user/site-lisp/irony-20170821.1300/build/docs/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/user/.emacs.d/user/site-lisp/irony-20170821.1300/build/test/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/user/.emacs.d/user/site-lisp/irony-20170821.1300/build/test/elisp/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: irony-server, Configuration: Release x64 ------
3>------ Skipped Build: Project: Continuous, Configuration: Release x64 ------
3>Project not selected to build for this solution configuration 
4>------ Skipped Build: Project: Experimental, Configuration: Release x64 ------
4>Project not selected to build for this solution configuration 
5>------ Skipped Build: Project: Nightly, Configuration: Release x64 ------
5>Project not selected to build for this solution configuration 
6>------ Skipped Build: Project: NightlyMemoryCheck, Configuration: Release x64 ------
6>Project not selected to build for this solution configuration 
7>------ Skipped Build: Project: RUN_TESTS, Configuration: Release x64 ------
7>Project not selected to build for this solution configuration 
8>------ Skipped Build: Project: check, Configuration: Release x64 ------
8>Project not selected to build for this solution configuration 
9>------ Skipped Build: Project: doxygen, Configuration: Release x64 ------
9>Project not selected to build for this solution configuration 
2>Building Custom Rule C:/user/.emacs.d/user/site-lisp/irony-20170821.1300/server/src/CMakeLists.txt
2>CMake does not need to re-run because C:/user/.emacs.d/user/site-lisp/irony-20170821.1300/build/src/CMakeFiles/generate.stamp is up-to-date.
2>cl : Command line warning D9025: overriding '/EHs' with '/EHs-'
2>cl : Command line warning D9025: overriding '/EHc' with '/EHc-'
2>CommandLineParser.cpp
2>TemporaryFile.cpp
2>C:\user\.emacs.d\user\site-lisp\irony-20170821.1300\server\src\support\TemporaryFile.cpp(22): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt\stdlib.h(1199): note: see declaration of 'getenv'
2>Command.cpp
2>C:\user\.emacs.d\user\site-lisp\irony-20170821.1300\server\src\Command.cpp(244): warning C4244: 'initializing': conversion from '__int64' to 'int', possible loss of data
2>C:\user\.emacs.d\user\site-lisp\irony-20170821.1300\server\src\Command.cpp(244): warning C4244: 'initializing': conversion from '__int64' to 'const int', possible loss of data
2>Irony.cpp
2>C:\user\.emacs.d\user\site-lisp\irony-20170821.1300\server\src\Irony.cpp(272): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
2>C:\user\.emacs.d\user\site-lisp\irony-20170821.1300\server\src\Irony.cpp(310): error C2446: ':': no conversion from '`anonymous-namespace'::startsWith::<lambda_7433bbf13b0f64e6ef14f264387985d3>' to '`anonymous-namespace'::startsWith::<lambda_a3bc2490bf28c7ef042d0572bcbe3f27>'
2>C:\user\.emacs.d\user\site-lisp\irony-20170821.1300\server\src\Irony.cpp(310): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
2>C:\user\.emacs.d\user\site-lisp\irony-20170821.1300\server\src\Irony.cpp(312): error C3536: 'charCmp': cannot be used before it is initialized
2>C:\user\.emacs.d\user\site-lisp\irony-20170821.1300\server\src\Irony.cpp(463): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
2>C:\user\.emacs.d\user\site-lisp\irony-20170821.1300\server\src\Irony.cpp(465): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
2>C:\user\.emacs.d\user\site-lisp\irony-20170821.1300\server\src\Irony.cpp(480): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
2>C:\user\.emacs.d\user\site-lisp\irony-20170821.1300\server\src\Irony.cpp(528): warning C4267: '=': conversion from 'size_t' to 'unsigned long', possible loss of data
2>TUManager.cpp
2>C:\user\.emacs.d\user\site-lisp\irony-20170821.1300\server\src\TUManager.cpp(115): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
2>C:\user\.emacs.d\user\site-lisp\irony-20170821.1300\server\src\TUManager.cpp(139): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
2>Generating Code...
2>Done building project "irony-server.vcxproj" -- FAILED.
10>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
10>Building Custom Rule C:/user/.emacs.d/user/site-lisp/irony-20170821.1300/server/CMakeLists.txt
10>CMake does not need to re-run because C:/user/.emacs.d/user/site-lisp/irony-20170821.1300/build/CMakeFiles/generate.stamp is up-to-date.
11>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
11>Project not selected to build for this solution configuration 
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 8 skipped ==========

**Comment by Abergard** [comment]
I have forgotten to mention that it is a fix only for Window compilation with Clang, not MSVC compiler. If I had more time I would try to fix MSVC compilation too.

**Comment by Abergard** [comment]
There was a problem with lambda deduction type. Both lambdas have nothing captured by [] and should be deduced to function pointer, however it may be a msvc bug.
@mambolevis , please check now

**Comment by mambolevis** [comment]
Question: 
is there any branch for testing it?

**Comment by mambolevis** [comment]
It works. Thank you!

**Comment by Sarcasm** [comment]
Arf, it's a pity that the isSensitive check is now done once per char instead of once per candidate but if it pleases MSVC, let's go for it.

Thank you for fixing this!

**Pull request merged**
