### PR TITLE
Support for compile_flags.txt

### LINKED ISSUE #489: support compile_flags.txt
Recent clang supports a `compile_flags.txt` file which can be used as an alternative to `compilation-database.json`. Quoting from https://clang.llvm.org/docs/JSONCompilationDatabase.html#build-system-integration

> ### Alternatives
> For simple projects, Clang tools also recognize a compile_flags.txt file. This should contain one flag per line. The same flags will be used to compile any file.

It would be nice when irony-mode would support this file.

### PR DESCRIPTION
**Pull request by vaivaswatha**
This addresses the comment in #505, which looks to be abandoned.

Closes #489.

### CODE REVIEW

**Comment by Sarcasm** [comment]
Thanks!
It's slightly better than the previous one, but there is still 2 traversals if the user is using `compile_flags.txt`.
I'm pretty one call to `locate-dominating-file` is sufficient, can you try that?

**Comment by vaivaswatha** [comment]
> Thanks!
> It's slightly better than the previous one, but there is still 2 traversals if the user is using `compile_flags.txt`.
> I'm pretty one call to `locate-dominating-file` is sufficient, can you try that?

Done.

**Comment by Sarcasm** [comment]
Just a thought, as I feel like this could simplify the code even further (but could be wrong).

Can you `throw` from the `locate-dominating-file` function, and return the value if you catch any?
Also, I would favor looking for `.compile_flags.txt` first, as it is now a somewhat standard file, documented by Clang itself.

If you don't think it's worth it, I'm ok merging the code as-is.

**Comment by vaivaswatha** [comment]
> Just a thought, as I feel like this could simplify the code even further (but could be wrong).
> 
> Can you `throw` from the `locate-dominating-file` function, and return the value if you catch any?
> Also, I would favor looking for `.compile_flags.txt` first, as it is now a somewhat standard file, documented by Clang itself.
> 
> If you don't think it's worth it, I'm ok merging the code as-is.

Pushed both the changes you suggested.

**Comment by Sarcasm** [comment]
Great!
I think the last thing that could have been improved is the double-ifs.
Using a `when`, `cond` or maybe `pcase` could make this part slightly more succinct.

Thank you for your time and effort. :+1:

**Pull request merged**
